src/br/com/devmedia/primefacesehibernate/model/Empresa.java
package br.com.devmedia.primefacesehibernate.model;

import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Inheritance;
import javax.persistence.InheritanceType;

@Entity
@Inheritance(strategy = InheritanceType.JOINED)
public abstract class Empresa {

	@Id
	private String CNPJ;
	private String razaoSocial;
	private String logradouro;
	private Integer numero;
	private String complemento;
	private String municipio;
	private String uf;
	private String telefone;
	private String email;

	public String getTipo() {
		return "";
	}
	
	public String getCNPJ() {
		return CNPJ;
	}

	public void setCNPJ(String cNPJ) {
		CNPJ = cNPJ;
	}

	public String getRazaoSocial() {
		return razaoSocial;
	}

	public void setRazaoSocial(String razaoSocial) {
		this.razaoSocial = razaoSocial;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public Integer getNumero() {
		return numero;
	}

	public void setNumero(Integer numero) {
		this.numero = numero;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getMunicipio() {
		return municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public String getUf() {
		return uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Override
	public String toString() {
		return "Empresa [CNPJ=" + CNPJ + ", razaoSocial=" + razaoSocial + ", logradouro=" + logradouro + ", numero="
				+ numero + ", complemento=" + complemento + ", municipio=" + municipio + ", uf=" + uf + ", telefone="
				+ telefone + ", email=" + email + "]";
	}

}

src/br/com/devmedia/primefacesehibernate/model/Filial.java
package br.com.devmedia.primefacesehibernate.model;

import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

@Entity
@Table
public class Filial extends Empresa {

	@ManyToOne(fetch = FetchType.EAGER)
	private Matriz matriz;

	public Matriz getMatriz() {
		return matriz;
	}

	public void setMatriz(Matriz matriz) {
		this.matriz = matriz;
	}

	@Override
	public String toString() {
		return "Filial [matriz=" + matriz + "]";
	}

}

src/br/com/devmedia/primefacesehibernate/model/Matriz.java
package br.com.devmedia.primefacesehibernate.model;

import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

@Entity
@Table
public class Matriz extends Empresa {

	@ManyToMany(fetch = FetchType.EAGER, mappedBy = "matriz", cascade = CascadeType.REMOVE)
	private Set<Filial> filiais;

	public Set<Filial> getFiliais() {
		return filiais;
	}

	public void setFiliais(Set<Filial> filiais) {
		this.filiais = filiais;
	}

	@Override
	public String toString() {
		return "Matriz [filiais=" + filiais + "]";
	}

}

WebContent/index.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>
	Test:
	<h:outputText value="#{empresa.test}" />
	
	<p:outputLabel value="#{empresa.msg}" id="msg1" styleClass="msg" />

	<p:dataTable emptyMessage="Não há empresas cadastradas"
		value="#{empresa.listaEmpresas}" var="e" styleClass="order-table"
		headerClass="order-table-header"
		rowClasses="order-table-odd-row,order-table-even-row" paginator="true"
		rows="20">
		<p:column headerText="CNPJ" sortBy="#{e.empresa.CNPJ}" filterBy="#{e.empresa.CNPJ}"
			filterMatchMode="exact">
			<h:outputText value="#{e.empresa.CNPJ}" />
		</p:column>
		<p:column headerText="Razão Social" sortBy="#{e.empresa.razaoSocial}"
			filterBy="#{e.empresa.razaoSocial}" filterMatchMode="exact">
			<h:outputText value="#{e.empresa.razaoSocial}" />
		</p:column>
		<p:column headerText="UF" sortBy="#{e.empresa.uf}" filterBy="#{e.empresa.uf}"
			filterMatchMode="exact">
			<h:outputText value="#{e.empresa.uf}" />
		</p:column>
		<p:column headerText="Município" sortBy="#{e.empresa.municipio}"
			filterBy="#{e.empresa.municipio}" filterMatchMode="exact">
			<h:outputText value="#{e.empresa.municipio}" />
		</p:column>
		<p:column>
			<f:facet name="header">
                    Filial
                    </f:facet>
             #{e.empresa.tipo}
       </p:column>
		<p:column>
			<h:form id="commandForm">

				<h:commandButton value="Delete" styleClass="fs-button-portfolio"
					action="#{empresa.delete}" ajax="false">
					<f:setPropertyActionListener target="#{empresa.selectedCNPJ}"
						value="#{e.empresa.CNPJ}" />
				</h:commandButton>
				<h:commandButton value="Edit" styleClass="fs-button-portfolio"
					action="#{empresa.edit}" ajax="false">
					<f:setPropertyActionListener target="#{empresa.selectedCNPJ}"
						value="#{e.empresa.CNPJ}" />
				</h:commandButton>

			</h:form>
		</p:column>
	</p:dataTable>
</h:body>
</html>

WebContent/insert.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" 
 "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
	xmlns:h="http://java.sun.com/jsf/html"
	xmlns:f="http://java.sun.com/jsf/core"
	xmlns:ui="http://java.sun.com/jsf/facelets"
	xmlns:p="http://primefaces.org/ui">
<h:head>
</h:head>
<h:body>

	<p:outputLabel value="#{empresa.msg}" id="msg1" styleClass="msg" />

	<h:form id="empresaForm" enctype="multipart/form-data"
		prependId="false">

		<p:panelGrid id="panel1" columns="3" border="3" cellpadding="5"
			cellspacing="1">
			<f:facet name="header">
				<h:outputText value="Criar empresa" />
			</f:facet>

			<p:outputLabel value="Tipo:" />
			<p:selectOneRadio id="matrizFilial" value="#{empresa.matrizFilial}">
				<f:selectItem itemValue="true" itemLabel="Matriz" />
				<f:selectItem itemValue="false" itemLabel="Filial" />
				<f:ajax event="change" execute="@this" render="panel1" />
			</p:selectOneRadio>
			<p:message for="matrizFilial" />

			<p:outputLabel value="Selecionar matriz:"
				rendered="#{empresa.matrizFilial eq 'false'}" />
			<p:selectOneMenu id="matrizes" value="#{empresa.matriz}"
				rendered="#{empresa.matrizFilial eq 'false'}">
				<f:selectItems value="#{empresa.listaMatrizes}" var="e"
					itemLabel="#{e.CNPJ}" itemValue="#{e.CNPJ}" />
			</p:selectOneMenu>
			<p:message for="matrizes"
				rendered="#{empresa.matrizFilial eq 'false'}" />

			<p:outputLabel value="Razao social:" />
			<p:inputText value="#{empresa.razaoSocial}" id="razaoSocial"
				maxlength="100" required="true" requiredMessage="Campo obrigatório" />
			<p:message for="razaoSocial" />

			<p:outputLabel value="CNPJ:" />
			<p:inputText value="#{empresa.CNPJ}" required="true" id="CNPJ"
				validatorMessage="CNPJ mal formatado"
				requiredMessage="Campo obrigatório">
				<f:validateRegex
					pattern="^[0-9]{2,3}\.[0-9]{3} 
                            \.[0-9]{3}\/[0-9]{4}-[0-9]{2}$" />
			</p:inputText>
			<p:message for="CNPJ" />

			<p:outputLabel value="Logradouro:" required="true" />
			<p:inputText value="#{empresa.logradouro}" id="logradouro"
				maxlength="150" required="true" requiredMessage="Campo obrigatório" />
			<p:message for="logradouro" />

			<p:outputLabel value="Número:" />
			<p:inputText value="#{empresa.numero}" id="numero" required="true"
				requiredMessage="Campo obrigatório" maxlength="10">
				<f:convertNumber integerOnly="true" type="number" />
			</p:inputText>
			<p:message for="numero" />

			<p:outputLabel value="Complemento:" />
			<p:inputText value="#{empresa.complemento}" id="complemento" />
			<p:message for="complemento" />

			<p:outputLabel value="Município:" />
			<p:inputText value="#{empresa.municipio}" id="municipio"
				maxlength="150" required="true" requiredMessage="Campo obrigatório" />
			<p:message for="municipio" />

			<p:outputLabel value="UF:" />
			<p:inputText value="#{empresa.uf}" id="uf" maxlength="2"
				required="true" requiredMessage="Campo obrigatório" />
			<p:message for="uf" />

			<p:outputLabel value="Telefone:" />
			<p:inputText value="#{empresa.telefone}" id="telefone1"
				required="true" requiredMessage="Campo obrigatório"
				validatorMessage="Telefone mal formatado. Ex. (99) 9999-9999">
			</p:inputText>

			<p:message for="telefone" />

			<p:outputLabel value="Telefone 2:" />
			<p:inputText value="#{empresa.telefone2}" id="telefone2"
				validatorMessage="Telefone mal formatado. Ex. (99) 9999-9999">

				<f:validateRegex
					pattern="^[+][9][0-9]{2}(\(11\) [9][0-9]
                                   {4}-[0-9]{4})|(\(1[2-9]\) [5-9][0-9]{3}-[0-9]{4})|
                                   (\([2-9][1-9]\) [5-9][0-9]{3}-[0-9]{4})$" />
			</p:inputText>
			<p:message for="telefone2" />

			<p:outputLabel value="Email" />
			<p:inputText id="email" value="#{empresa.email}" label="email"
				size="40" validatorMessage="Email mal formatado">

				<f:validateRegex
					pattern="^[_A-Za-z0-9-\+]+(\.[_A-Za-z0-9-]+)*
                                  @[A-Za-z0-9-]+(\.[A-Za-z0-9]+)*(\.[A-Za-z]{2,})$" />

			</p:inputText>
			<p:message for="email" />

			<f:facet name="footer">
				<h:commandButton value="Salvar" action="#{empresa.createEmpresa}"
					update="empresaForm">
				</h:commandButton>
			</f:facet>

		</p:panelGrid>
	</h:form>

</h:body>
</html>

WebContent/update.xhtml
<f:facet name="footer">
	<h:commandButton value="Atualizar" update="empresaForm"
		action="#{empresa.updateEmpresa}">
		<f:ajax
			render="razaoSocial CNPJ logradouro numero complemento 
          municipio uf telefone1 telefone2 fax"
			execute="@form" />
	</h:commandButton>
</f:facet>